import "../styles/app.sass";

export const metadata = {
	title: "Juli Ramon – Frontend Developer",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
